int add (int, int);
int addi (int, int);
int or (int, int);
int and (int, int);
int xor (int, int);
int nor (int, int);
int sll (int, int);
int rot (int, int);
int bne (int, int);
int ldl (int);
int ldh (int);
int stl (int);
int sth (int);
int jmp (int);
int jal (int);
int jr (int);
int jalr (int);
int nop (?);
