## 
## -------------------------------------------------------------
##    Copyright 2010 Mentor Graphics Corporation
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

UVM_HOME	= /home/bl/mephi_kaf27_cpu_2015/testbench/uvm_test/uvm-1.2/src

include /home/bl/mephi_kaf27_cpu_2015/testbench/uvm_test/uvm-1.2/examples/simple/hello_world/Makefile.questa

all: run

comp: vlib
	$(VLOG) +incdir+. \
		hello_world.sv

run: comp
	$(VSIM)
	$(CHECK)
